[package]
name = "dislist"
version = "1.66.1"
edition = "2021"
author = "Ankush Mondal"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
